<?php

return [
    "76094472-6" => [
        "razon_social_nombre" => "Sociedad De Inversiones Atardeceres SA",
        "banco" => "Santander",
        "numero" => "67304136",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76188162-0" => [
        "razon_social_nombre" => "Living Acalis SpA",
        "banco" => "Santander",
        "numero" => "70514788",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76434639-4" => [
        "razon_social_nombre" => "Living Candil SpA",
        "banco" => "Santander",
        "numero" => "69397670",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76106821-0" => [
        "razon_social_nombre" => "Seniority Chile SA",
        "banco" => "Santander",
        "numero" => "64734873",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76094472-6" => [
        "razon_social_nombre" => "Servicios Médicos Y Enfermería SpA",
        "banco" => "Santander",
        "numero" => "7306312-4",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76434651-3" => [
        "razon_social_nombre" => "Living Coventry SpA",
        "banco" => "ITAÚ",
        "numero" => "70514788",
        "tipo_de_cuenta" => "Corriente",
    ],
    "50545730-7" => [
        "razon_social_nombre" => "Residencia Casactiva SpA",
        "banco" => "Santander",
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "96577310-K" => [
        "razon_social_nombre" => "Andes Airport Services SA",
        "banco" => "Santander",
        "numero" => "591213-0",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76611528-4" => [
        "razon_social_nombre" => "Acciona Airport Services Chile SpA",
        "banco" => "Santander",
        "numero" => "7221420-0",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76973051-6" => [
        "razon_social_nombre" => "Acciona Airport Americas SpA",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "96870370-6" => [
        "razon_social_nombre" => "Accor Chile SA",
        "banco" => "Santander",
        "numero" => "0-000-6967578-6",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76502610-5" => [
        "razon_social_nombre" => "Accor Pdch SpA",
        "banco" => "Santander",
        "numero" => "0-000-7424293-6",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76116569-0" => [
        "razon_social_nombre" => "Inmobiliaria Nueva Apoquindo SA",
        "banco" => "Santander",
        "numero" => "0-000-7263681-3",
        "tipo_de_cuenta" => "Corriente",
    ],
    "79528420-6" => [
        "razon_social_nombre" => "Ingenieria Agrosonda SpA",
        "banco" => "Santander",
        "numero" => "9003827",
        "tipo_de_cuenta" => "Corriente",
    ],
    "61808000-5" => [
        "razon_social_nombre" => "Aguas Andinas, SA",
        "banco" => "Banco de Chile",
        "numero" => "41801-03",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96809310-K" => [
        "razon_social_nombre" => "Aguas Cordillera SA",
        "banco" => "Banco de Chile",
        "numero" => "164-25324-06",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76190084-6" => [
        "razon_social_nombre" => "Aguas Del Maipo SA",
        "banco" => "Banco de Chile",
        "numero" => "89343-08",
        "tipo_de_cuenta" => "Corriente",
    ],
    "89221000-4" => [
        "razon_social_nombre" => "Aguas Manquehue SA",
        "banco" => "Banco de Chile",
        "numero" => "11325-05",
        "tipo_de_cuenta" => "Corriente",
    ],
    "65113732-2" => [
        "razon_social_nombre" => "Corporación Chilena De Investigación Del Agua",
        "banco" => "Banco de Chile",
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "96967550-1" => [
        "razon_social_nombre" => "Análisis Ambientales SA",
        "banco" => "Banco de Chile",
        "numero" => "800-00819-07",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96945210-3" => [
        "razon_social_nombre" => "Ecoriles SA",
        "banco" => "Banco de Chile",
        "numero" => "800-00818-09",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96828120-8" => [
        "razon_social_nombre" => "Gestión Y Servicios SA",
        "banco" => "Banco de Chile",
        "numero" => "88876-01",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76418976-0" => [
        "razon_social_nombre" => "Aguas Antofagasta SA",
        "banco" => "BCI",
        "numero" => "10530622",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96590530-8" => [
        "razon_social_nombre" => "Air Liquide Chile SA",
        "banco" => "Scotiabank (BBVA AZUL)",
        "numero" => "0504-0042-0100004304",
        "tipo_de_cuenta" => "Corriente",
    ],
    "80889200-6" => [
        "razon_social_nombre" => "Alstom Chile SA",
        "banco" => "BBVA",
        "numero" => "180100053789",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76881650-6 " => [
        "razon_social_nombre" => "Alternattiva EST Ltda",
        "banco" => "BCI",
        "numero" => "35402067",
        "tipo_de_cuenta" => "Corriente",
    ],
    "79777010-8 " => [
        "razon_social_nombre" => "Marketing y Promociones S.A",
        "banco" => "BCI",
        "numero" => "84009438",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77774700-2" => [
        "razon_social_nombre" => "Sociedad De Aseo Profesional Ltda",
        "banco" => "Santander",
        "numero" => "04-78010-8",
        "tipo_de_cuenta" => "Corriente",
    ],
    "82531700-7" => [
        "razon_social_nombre" => "Asociación Chilena De Protección A La Familia",
        "banco" => "Santander",
        "numero" => "3091700-6",
        "tipo_de_cuenta" => "Corriente",
    ],
    "80893200-8" => [
        "razon_social_nombre" => "Arrigoni Metalurgica SA",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "96535280-5" => [
        "razon_social_nombre" => "Servicios Industriales SpA",
        "banco" => "Banco Estado",
        "numero" => "1300072905",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76135131-1" => [
        "razon_social_nombre" => "Aurora Australis SA",
        "banco" => "BCI",
        "numero" => "23081589",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96821540-K" => [
        "razon_social_nombre" => "Baron Philippe De Rothschild Maipo Chile SA",
        "banco" => "Banco de Chile",
        "numero" => "00-176-01816-06",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76117617-K" => [
        "razon_social_nombre" => "Constructora Befco SA",
        "banco" => "Santander",
        "numero" => "65658135",
        "tipo_de_cuenta" => "Corriente",
    ],
    "84060600-7" => [
        "razon_social_nombre" => "Constructora De Pavimentos Asfalticos Bitumix SA",
        "banco" => "Banco de Chile",
        "numero" => "1786747002",
        "tipo_de_cuenta" => "Corriente",
    ],
    "81013400-3" => [
        "razon_social_nombre" => "Bombones Varsovienne",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "79750620-6" => [
        "razon_social_nombre" => "Selección, Contratación y Servicios S.A",
        "banco" => "Banco de Chile",
        "numero" => "1590499406",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76511591-4" => [
        "razon_social_nombre" => "Buro EST Ltda",
        "banco" => "Banco de Chile",
        "numero" => "8001386403",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76714250-1" => [
        "razon_social_nombre" => "BuroTemps Empresa De Servicios Transitorios Limitada",
        "banco" => "Banco de Chile",
        "numero" => "4720031610",
        "tipo_de_cuenta" => "Corriente",
    ],
    "85969100-5" => [
        "razon_social_nombre" => "Manufacturas Eléctricas Byp Ltda",
        "banco" => "Banco de Chile",
        "numero" => "1804708107",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78793360-2" => [
        "razon_social_nombre" => "Sociedad De Alimentación Casino Express SA",
        "banco" => "Security",
        "numero" => "19535922",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77588670-6" => [
        "razon_social_nombre" => "Inversiones Y Servicios Stc Limitada",
        "banco" => "Banco de Chile",
        "numero" => "1591591408",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77115570-7" => [
        "razon_social_nombre" => "Servicios Y Comercial Rauco Ltda",
        "banco" => "Banco de Chile",
        "numero" => "1591138006",
        "tipo_de_cuenta" => "Corriente",
    ],
    "79746250-0" => [
        "razon_social_nombre" => "Elaboradora De Alimentos Frutale Ltda",
        "banco" => "Banco de Chile",
        "numero" => "1591092310",
        "tipo_de_cuenta" => "Corriente",
    ],
    "83515400-9" => [
        "razon_social_nombre" => "Logistica Providencia Ltda",
        "banco" => "Banco de Chile",
        "numero" => "1591132405",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76872560-8" => [
        "razon_social_nombre" => "Cobra Chile Servicios SA",
        "banco" => "Santander",
        "numero" => "64879995",
        "tipo_de_cuenta" => "Corriente",
    ],
    "79605540-5" => [
        "razon_social_nombre" => "Comercial Successo Ltda (Castro)",
        "banco" => "Santander",
        "numero" => "17-5700931-4",
        "tipo_de_cuenta" => "Corriente",
    ],
    "79605540-6" => [
        "razon_social_nombre" => "Comercial Successo Ltda (Almirante Pastene)",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "99575630-7" => [
        "razon_social_nombre" => "010 Empresa Conpax SA",
        "banco" => "Banco de Chile",
        "numero" => "000-23257-02",
        "tipo_de_cuenta" => "Corriente",
    ],
    "79637370-9" => [
        "razon_social_nombre" => "100 Constructora Conpax",
        "banco" => "Banco de Chile",
        "numero" => "000-76077-09",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76050655-9" => [
        "razon_social_nombre" => "101 Conpax Edificación",
        "banco" => "Banco de Chile",
        "numero" => "000-74036-05",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78301280-4" => [
        "razon_social_nombre" => "200 Conpax Inmobiliaria",
        "banco" => "Banco de Chile",
        "numero" => "000-41176-00",
        "tipo_de_cuenta" => "Corriente",
    ],
    "99511310-4" => [
        "razon_social_nombre" => "300 Minería Y Montajes Conpax",
        "banco" => "Banco de Chile",
        "numero" => "7008501",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76046493-7" => [
        "razon_social_nombre" => "400 Conpax Energía Y Concesiones SpA",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "78016820-K" => [
        "razon_social_nombre" => "500 Conpax Maquinarias SpA",
        "banco" => "Banco de Chile",
        "numero" => "00-5569407",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76045728-0" => [
        "razon_social_nombre" => "600 Conpax Administración SpA",
        "banco" => "Banco de Chile",
        "numero" => "000-77820-06",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96542940-9" => [
        "razon_social_nombre" => "Constructora Ecopsa SA",
        "banco" => "Santander",
        "numero" => "4036442-0 ",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76961000-6" => [
        "razon_social_nombre" => "Constructora Ecora SA",
        "banco" => "Scotiabank",
        "numero" => "30039424",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96528140-1 " => [
        "razon_social_nombre" => "Constructora Lyd SA",
        "banco" => "Banco de Chile",
        "numero" => "2800754702",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96528140-1 " => [
        "razon_social_nombre" => "Constructora Lyd SA",
        "banco" => "Banco de Chile",
        "numero" => "58997-07",
        "tipo_de_cuenta" => "Corriente",
    ],
    "92909000-4" => [
        "razon_social_nombre" => "Automotriz Curifor SA",
        "banco" => "Banco de Chile",
        "numero" => "01941-00",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76004048-7" => [
        "razon_social_nombre" => "Dartel Copiapo Limitada",
        "banco" => "Banco de Chile",
        "numero" => "00-000-29317-02",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76037760-0" => [
        "razon_social_nombre" => "Darlux Limitada",
        "banco" => "Banco de Chile",
        "numero" => "00-000-95018-01",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76104425-7" => [
        "razon_social_nombre" => "Dartel Temuco Limitada",
        "banco" => "Banco de Chile",
        "numero" => "8925310",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76216797-2" => [
        "razon_social_nombre" => "Dartel La Serena Limitada",
        "banco" => "Banco de Chile",
        "numero" => "9952704",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76242231-K" => [
        "razon_social_nombre" => "Dartel Rancagua Limitada",
        "banco" => "Banco de Chile",
        "numero" => "8584004",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76410129-4" => [
        "razon_social_nombre" => "Logistica Los Libertadores Limitada",
        "banco" => "Banco de Chile",
        "numero" => "00-800-08203-06",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76483565-4" => [
        "razon_social_nombre" => "Tableros Y Soluciones Electricas SpA",
        "banco" => "Banco de Chile",
        "numero" => "00-800-12029-09",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76524230-4" => [
        "razon_social_nombre" => "Dartel Calama Limitada",
        "banco" => "Banco de Chile",
        "numero" => "00-000-65496-05",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76545467-0" => [
        "razon_social_nombre" => "Comercial Light Room SpA",
        "banco" => "Banco de Chile",
        "numero" => "00-800-14858-04",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76795234-1" => [
        "razon_social_nombre" => "Dartel Los Libertadores Limitada",
        "banco" => "Banco de Chile",
        "numero" => "00-800-24132-00",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77029536-k" => [
        "razon_social_nombre" => "Dartel Valdivia Limitada",
        "banco" => "Banco de Chile",
        "numero" => "8003696405",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77425090-5" => [
        "razon_social_nombre" => "Dartel Puerto Montt Limitada",
        "banco" => "Banco de Chile",
        "numero" => "1710576000",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78360030-7" => [
        "razon_social_nombre" => "Dartel Antofagasta Limitada",
        "banco" => "Banco de Chile",
        "numero" => "1100441108",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78480270-1" => [
        "razon_social_nombre" => "Dartel Talca Limitada",
        "banco" => "Banco de Chile",
        "numero" => "00-171-20034-09",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78645100-0" => [
        "razon_social_nombre" => "Dartel Iquique Limitada",
        "banco" => "Banco de Chile",
        "numero" => "00-171-02346-03",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78775860-6" => [
        "razon_social_nombre" => "Dartel Concepcion Limitada",
        "banco" => "Banco de Chile",
        "numero" => "2250057610",
        "tipo_de_cuenta" => "Corriente",
    ],
    "79827650-6" => [
        "razon_social_nombre" => "Darco Limitada",
        "banco" => "Banco de Chile",
        "numero" => "00-171-04870-09",
        "tipo_de_cuenta" => "Corriente",
    ],
    "87773200-2" => [
        "razon_social_nombre" => "Dartel Valparaiso Limitada",
        "banco" => "Banco de Chile",
        "numero" => "1026570902",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96659260-5" => [
        "razon_social_nombre" => "Transportes Dartel SA",
        "banco" => "Banco de Chile",
        "numero" => "1710655507",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96806110-0" => [
        "razon_social_nombre" => "Dartel SA",
        "banco" => "Banco de Chile",
        "numero" => "1710124100",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96551880-0" => [
        "razon_social_nombre" => "Dhl Global Forwarding Chile SA",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "96694680-6" => [
        "razon_social_nombre" => "Diana Food Chile SPA",
        "banco" => "Santander",
        "numero" => "7504359-7",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77663150-7" => [
        "razon_social_nombre" => "Hotelera Diego De Almagro Ltda",
        "banco" => "Santander",
        "numero" => "283851",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77562000-5" => [
        "razon_social_nombre" => "Hotelera Holanda Ltda",
        "banco" => "Santander",
        "numero" => "67939433",
        "tipo_de_cuenta" => "Corriente",
    ],
    "79743490-6" => [
        "razon_social_nombre" => "Comercial Maifa Ltda",
        "banco" => "Santander",
        "numero" => "40173943",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96824110-9" => [
        "razon_social_nombre" => "Disal Chile Sanitarios Portables SA",
        "banco" => "BCI",
        "numero" => "12797529",
        "tipo_de_cuenta" => "Corriente",
    ],
    "79943018-0" => [
        "razon_social_nombre" => "Disal Chile Servicios Integrales SA",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "76008989-3" => [
        "razon_social_nombre" => "Distribuidora De Combustibles Petroamérica, SA",
        "banco" => "Santander",
        "numero" => "6238339-9",
        "tipo_de_cuenta" => "Corriente",
    ],
    "79705390-2" => [
        "razon_social_nombre" => "Transportes Santa María SpA",
        "banco" => "Santander",
        "numero" => "28945-0",
        "tipo_de_cuenta" => "Corriente",
    ],
    "90193000-7" => [
        "razon_social_nombre" => "Empresa El Mercurio SpA",
        "banco" => "Banco de Chile",
        "numero" => "3158304",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96896480-1" => [
        "razon_social_nombre" => "Electrafk, SA",
        "banco" => "Banco de Chile",
        "numero" => "4720013100",
        "tipo_de_cuenta" => "Corriente",
    ],
    "93720000-5" => [
        "razon_social_nombre" => "Flores Y Kersting, SA",
        "banco" => "Banco de Chile",
        "numero" => "4720013002",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96553830-5" => [
        "razon_social_nombre" => "Entel Contact Center SA",
        "banco" => "BCI",
        "numero" => "10464883",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96563570-K" => [
        "razon_social_nombre" => "Entel Call Center SA",
        "banco" => "BCI",
        "numero" => "10464883",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96672640-7" => [
        "razon_social_nombre" => "Entel Servicios Empresariales SA",
        "banco" => "Banco de Chile",
        "numero" => "160025137",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96579800-5" => [
        "razon_social_nombre" => "Essal SA",
        "banco" => "Santander",
        "numero" => "8267010227",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77038708-6" => [
        "razon_social_nombre" => "Inneria Chile SpA",
        "banco" => "Santander",
        "numero" => "74561357",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77038711-6" => [
        "razon_social_nombre" => "Eurofirms Chile Est SpA",
        "banco" => "Santander",
        "numero" => "74572588",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76868865-6" => [
        "razon_social_nombre" => "Exprocap S.A",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "76024303-5" => [
        "razon_social_nombre" => "EST Exproservicios S.A",
        "banco" => "BCI",
        "numero" => "35405635",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76734280-2" => [
        "razon_social_nombre" => "EST Exprotempo S.A",
        "banco" => "BCI",
        "numero" => "35400803",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76865650-9" => [
        "razon_social_nombre" => "Exproservicios SpA",
        "banco" => "BCI",
        "numero" => "35402873",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76293090-0" => [
        "razon_social_nombre" => "Expro Chile S.A",
        "banco" => "BCI",
        "numero" => "32318120",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77092620-3" => [
        "razon_social_nombre" => "Rivas y Asociados S.A",
        "banco" => "BCI",
        "numero" => "11644591",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78036610-9" => [
        "razon_social_nombre" => "Servicios De Esxportación Fruticolas Exser Ltda",
        "banco" => "Santander",
        "numero" => "0-000-0092621-3 ",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78611990-1" => [
        "razon_social_nombre" => "Agroindustrial Codigua SpA",
        "banco" => "Santander",
        "numero" => "0074-00459392",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76009092-1" => [
        "razon_social_nombre" => "Transportes Kumey SpA",
        "banco" => "Santander",
        "numero" => "6183878-3",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77471270-4" => [
        "razon_social_nombre" => "Agrocomercial Codigua SpA",
        "banco" => "Santander",
        "numero" => "0074-0100188-8",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76716680-K" => [
        "razon_social_nombre" => "Lacteos Del Sur SA",
        "banco" => "Santander",
        "numero" => "641091-0",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78611990-1" => [
        "razon_social_nombre" => "Lacteos Kumey",
        "banco" => "Santander",
        "numero" => "61834575",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76072221-9" => [
        "razon_social_nombre" => "Transportes Codigua SpA",
        "banco" => "Santander",
        "numero" => "6318379-2",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76479534-2" => [
        "razon_social_nombre" => "Aventura Outdoor SpA",
        "banco" => "Banco de Chile",
        "numero" => "851-02907-08",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76036599-8" => [
        "razon_social_nombre" => "Gastronomica Di Como SA",
        "banco" => "Banco de Chile",
        "numero" => "851-02296-00",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76558396-9" => [
        "razon_social_nombre" => "Hotel Noi Blend Ltda",
        "banco" => "Banco de Chile",
        "numero" => "851-03022-10",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76379700-7" => [
        "razon_social_nombre" => "Hotel Noi Casa Atacama Ltda",
        "banco" => "Banco de Chile",
        "numero" => "851-02009-07",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76153534-K" => [
        "razon_social_nombre" => "Hotel Noi Patagonia Ltda",
        "banco" => "Banco de Chile",
        "numero" => "851-02327-04",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76036597-1" => [
        "razon_social_nombre" => "Importadora Globaldis SA",
        "banco" => "Banco de Chile",
        "numero" => "851-02851-09",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76247542-1" => [
        "razon_social_nombre" => "Importadora Potenza SpA",
        "banco" => "Banco de Chile",
        "numero" => "851-02600-01",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76644880-1" => [
        "razon_social_nombre" => "Inmobiliaria Albatros SA",
        "banco" => "Banco de Chile",
        "numero" => "851-01466-06",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96584690-5" => [
        "razon_social_nombre" => "Inmobiliaria Tierras Blancas Ltda",
        "banco" => "Banco de Chile",
        "numero" => "851-01326-00",
        "tipo_de_cuenta" => "Corriente",
    ],
    "99579040-8" => [
        "razon_social_nombre" => "Inversiones Bergamo Ltda",
        "banco" => "Banco de Chile",
        "numero" => "881-00499-05",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76094014-3" => [
        "razon_social_nombre" => "Noi Hotels SA",
        "banco" => "Banco de Chile",
        "numero" => "851-02253-07",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76188859-5" => [
        "razon_social_nombre" => "Noi Puma Lodge SA",
        "banco" => "Banco de Chile",
        "numero" => "851-02471-08",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76127859-2" => [
        "razon_social_nombre" => "Noi Vitacura Ltda",
        "banco" => "Banco de Chile",
        "numero" => "851-02240-05",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76188868-4" => [
        "razon_social_nombre" => "Operadora Turistica Heliski SA",
        "banco" => "Banco de Chile",
        "numero" => "851-02475-00",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76409424-7" => [
        "razon_social_nombre" => "Palermo SpA",
        "banco" => "ITAÚ",
        "numero" => "203992180",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76188859-5" => [
        "razon_social_nombre" => "Puma Lodge SA",
        "banco" => "Banco de Chile",
        "numero" => "851-01945-05",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76536377-2" => [
        "razon_social_nombre" => "Tecno Noi SpA",
        "banco" => "Banco de Chile",
        "numero" => "851-03075-00",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76059308-7" => [
        "razon_social_nombre" => "Transporte Aereo Albatros Ltda",
        "banco" => "Banco de Chile",
        "numero" => "851-02430-00",
        "tipo_de_cuenta" => "Corriente",
    ],
    "93933000-3" => [
        "razon_social_nombre" => "Sociedad Pétreos SA",
        "banco" => "Banco de Chile",
        "numero" => "16309-00",
        "tipo_de_cuenta" => "Corriente",
    ],
    "91337000-7" => [
        "razon_social_nombre" => "Cemento Polpaico SA",
        "banco" => "Banco de Chile",
        "numero" => "16309-00",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76420230-9" => [
        "razon_social_nombre" => "Compañía Minera Polpaico Ltda",
        "banco" => "Banco de Chile",
        "numero" => "16309-00",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76309943-1" => [
        "razon_social_nombre" => "Modis SpA",
        "banco" => "Santander",
        "numero" => "70396629",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76157191-5" => [
        "razon_social_nombre" => "Rambrands SA",
        "banco" => "Santander",
        "numero" => "65313103",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76008957-5" => [
        "razon_social_nombre" => "Chile Moda SpA",
        "banco" => "Santander",
        "numero" => "63503495",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76402420-6" => [
        "razon_social_nombre" => "Comercial Ram ",
        "banco" => "Santander",
        "numero" => "5177200",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76247658-4" => [
        "razon_social_nombre" => "Premium SpA",
        "banco" => "Santander",
        "numero" => "66591395",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78829890-0" => [
        "razon_social_nombre" => "Ingenieria En Sanitización SA",
        "banco" => "Santander",
        "numero" => "10064473",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76360903-0" => [
        "razon_social_nombre" => "Rentokil Initial Chile SpA",
        "banco" => "Santander",
        "numero" => "61372725",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76169033-7" => [
        "razon_social_nombre" => "Fumigaciones Del Maule Limitada",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "76229937-2" => [
        "razon_social_nombre" => "Comercializadora De Insumos Y Servicios Mauco Limitada",
        "banco" => "Santander",
        "numero" => "66297691",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77466710-5" => [
        "razon_social_nombre" => "Sociedad Comercial Cleantech SpA",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "76245499-8" => [
        "razon_social_nombre" => "Control De Plagas Hidalgo Y Rodriguez Limitada",
        "banco" => "Santander",
        "numero" => "70734869",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76146691-7" => [
        "razon_social_nombre" => "Utendor SpA",
        "banco" => "BCI",
        "numero" => "35412160",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76618796-K" => [
        "razon_social_nombre" => "Barlovento SpA",
        "banco" => "BCI",
        "numero" => "35423609",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96794440-8" => [
        "razon_social_nombre" => "Heavenward Ascensores SA",
        "banco" => "BCI",
        "numero" => "18311962",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76477122-2" => [
        "razon_social_nombre" => "Hotelera Alameda SpA",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "76360678-3 " => [
        "razon_social_nombre" => "Hotelera Cordillera Luz SpA",
        "banco" => "ITAÚ",
        "numero" => "210491130",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76360669-4" => [
        "razon_social_nombre" => "Hotelera Luxe SpA",
        "banco" => "ITAÚ",
        "numero" => "429553819",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76499130-3" => [
        "razon_social_nombre" => "Servicios Hoteleros Starwood Ltda",
        "banco" => "ITAÚ",
        "numero" => "202245717",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76301099-6" => [
        "razon_social_nombre" => "Turismo Y Hoteles Vj Ltda",
        "banco" => "ITAÚ",
        "numero" => "208859944",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76320782-K" => [
        "razon_social_nombre" => "Hoteles Cumbres SpA",
        "banco" => "Santander",
        "numero" => "0-000-6811688-0",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76308711-5" => [
        "razon_social_nombre" => "Hotelera Patagonia Dos SA",
        "banco" => "Santander",
        "numero" => "0-000-6826117-1",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76320775-7" => [
        "razon_social_nombre" => "Hotelera Patagonia Tres SA",
        "banco" => "Santander",
        "numero" => "0-000-6814731-0",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76049144-6" => [
        "razon_social_nombre" => "Hotelera Patagonia SA",
        "banco" => "Santander",
        "numero" => "0-000-6274309-3",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76319008-0" => [
        "razon_social_nombre" => "Inversiones Surandino SA",
        "banco" => "Santander",
        "numero" => "0-000-6769360-4",
        "tipo_de_cuenta" => "Corriente",
    ],
    "784446860-7" => [
        "razon_social_nombre" => "Sociedad Hotelera Eurotel Ltda",
        "banco" => null,
        "numero" => "10530622",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76190174-5" => [
        "razon_social_nombre" => "Inmobiliaria Posh Ltda",
        "banco" => "BCI",
        "numero" => "30135842",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76042628-8" => [
        "razon_social_nombre" => "Inmobiliria Shine Ltda",
        "banco" => "BCI",
        "numero" => "30135834",
        "tipo_de_cuenta" => "Corriente",
    ],
    "99544140-3" => [
        "razon_social_nombre" => "Royal Santiago Hotel SA",
        "banco" => "BBVA",
        "numero" => "1640100010081",
        "tipo_de_cuenta" => "Corriente",
    ],
    "65078404-9" => [
        "razon_social_nombre" => "Ong De Desarrollo Medio Ambiental Ama Torres Del Paine",
        "banco" => "Santander",
        "numero" => "67891929",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76211752-5" => [
        "razon_social_nombre" => "Estancia Cerro Paine",
        "banco" => "ITAÚ",
        "numero" => "208833819",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76957040-3" => [
        "razon_social_nombre" => "Centro De Servicios Compartidos",
        "banco" => "ITAÚ",
        "numero" => "208833829",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77733880-3" => [
        "razon_social_nombre" => "Transportes Las Torres Ltda",
        "banco" => "ITAÚ",
        "numero" => "208653316",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78809700-K" => [
        "razon_social_nombre" => "Servicios Turisticos Fantastico Sur Ltda",
        "banco" => "ITAÚ",
        "numero" => "208780442",
        "tipo_de_cuenta" => "Corriente",
    ],
    "99575520-3" => [
        "razon_social_nombre" => "Hotel Las Torres De La Patgonia SA",
        "banco" => "ITAÚ",
        "numero" => "208551922",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76134579-6" => [
        "razon_social_nombre" => "Inmobiliaria Y Hotelera Pettra Concepcion S A",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "76134589-3" => [
        "razon_social_nombre" => "Inmobiliaria Y Hotelera Petra SA",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "78018550-3" => [
        "razon_social_nombre" => "Comercial Icom Ltda",
        "banco" => "Scotiabank",
        "numero" => "973527991",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77499120-4" => [
        "razon_social_nombre" => "Consultores y Proveedores en Outsourcing Ltda",
        "banco" => "Santander",
        "numero" => "420298",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76740220-1" => [
        "razon_social_nombre" => "Empresa de Servicios Transitorios Human Net Ltda",
        "banco" => "Santander",
        "numero" => "6273467",
        "tipo_de_cuenta" => "Corriente",
    ],
    "92654000-9" => [
        "razon_social_nombre" => "Hunter Douglas Chile SA",
        "banco" => "Banco de Chile",
        "numero" => "1883528800",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78080500-5" => [
        "razon_social_nombre" => "Persianas Andina Ltda",
        "banco" => "BCI",
        "numero" => "18003389",
        "tipo_de_cuenta" => "Corriente",
    ],
    "99504610-5" => [
        "razon_social_nombre" => "Incosec SA",
        "banco" => "BCI",
        "numero" => "10527192",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77630470-0" => [
        "razon_social_nombre" => "Incosegur",
        "banco" => "BCI",
        "numero" => "10475877",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77630810-2" => [
        "razon_social_nombre" => "Incoservicios",
        "banco" => "BCI",
        "numero" => "10475869",
        "tipo_de_cuenta" => "Corriente",
    ],
    "89681600-4" => [
        "razon_social_nombre" => "Sociedad Incosec Limitada",
        "banco" => "BCI",
        "numero" => "82032262",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76736400-8" => [
        "razon_social_nombre" => "Servicios Transitorios Limitada",
        "banco" => "BCI",
        "numero" => "10585494",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78730890-2" => [
        "razon_social_nombre" => "Procesadora Insuban SpA",
        "banco" => "Santander",
        "numero" => "09-05401-4",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96690870-K" => [
        "razon_social_nombre" => "Integrity SA",
        "banco" => "Banco de Chile",
        "numero" => "00-14836464-00",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76420039-K" => [
        "razon_social_nombre" => "San Pablo",
        "banco" => "Santander",
        "numero" => "73-72351-5",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76420036-5" => [
        "razon_social_nombre" => "Las Mercedes SpA",
        "banco" => "Santander",
        "numero" => "73-70270-4",
        "tipo_de_cuenta" => "Corriente",
    ],
    "80571500-6" => [
        "razon_social_nombre" => "Iss Servicios Generales Ltda",
        "banco" => "Banco de Chile",
        "numero" => "00-151-00290-08",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77718910-7" => [
        "razon_social_nombre" => "Iss Instituto De Formación Ltda",
        "banco" => "Bice",
        "numero" => "03-00946-7",
        "tipo_de_cuenta" => "Corriente",
    ],
    "89026000-4" => [
        "razon_social_nombre" => "Iss Facility Services, SA",
        "banco" => "Banco de Chile",
        "numero" => "00-159-19173-04",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78417060-8" => [
        "razon_social_nombre" => "Iss Servicios De Limpieza Industrial Ltda",
        "banco" => "Banco de Chile",
        "numero" => "00-226-06821-76",
        "tipo_de_cuenta" => "Corriente",
    ],
    "82612000-2" => [
        "razon_social_nombre" => "Iss Serviciosde Limpieza Mecanizada SA",
        "banco" => "Banco de Chile",
        "numero" => "00-159-22298-02",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77025900-2" => [
        "razon_social_nombre" => "Iss Servicios Integrales Ltda",
        "banco" => "Banco de Chile",
        "numero" => "00-110-01819-02",
        "tipo_de_cuenta" => "Corriente",
    ],
    "99559230-4" => [
        "razon_social_nombre" => "Iss Chile SA",
        "banco" => "Santander",
        "numero" => "63618551",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78234160-K" => [
        "razon_social_nombre" => "A Punto Servicios De Alimentación SA",
        "banco" => "Banco de Chile",
        "numero" => "1960100102",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76059472-5" => [
        "razon_social_nombre" => "Distribuidora Manantiales Ltda",
        "banco" => "Banco de Chile",
        "numero" => "8002019300",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76071717-7" => [
        "razon_social_nombre" => "Kallplat Chile Call Center Limitada",
        "banco" => "BCI",
        "numero" => "10614478",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76215357-2" => [
        "razon_social_nombre" => "Karcher Chile SpA",
        "banco" => "BCI",
        "numero" => "106 37 494",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76583350-7" => [
        "razon_social_nombre" => "Konecta Chile Ltda ",
        "banco" => "Santander",
        "numero" => "6395420-9",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76577390-3 " => [
        "razon_social_nombre" => "Chocolates Del Mundo SA",
        "banco" => "Banco de Chile",
        "numero" => "4720020007",
        "tipo_de_cuenta" => "Corriente",
    ],
    "93135000-5" => [
        "razon_social_nombre" => "Laboratorios Bagó de Chile SA",
        "banco" => "BCI",
        "numero" => "28100051",
        "tipo_de_cuenta" => "Corriente",
    ],
    "80478200-1" => [
        "razon_social_nombre" => "Ilop SA",
        "banco" => "Santander",
        "numero" => "6764056-0",
        "tipo_de_cuenta" => "Corriente",
    ],
    "99597910-1" => [
        "razon_social_nombre" => "Linker SpA",
        "banco" => "Banco de Chile",
        "numero" => "2700363108",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96995430-3" => [
        "razon_social_nombre" => "Inversiones La Gloria SA",
        "banco" => "Banco de Chile",
        "numero" => "00-162-08582-06",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76019055-1" => [
        "razon_social_nombre" => "Panaderia Lo Saldes San Carlos De Apoqu",
        "banco" => "Banco de Chile",
        "numero" => "00-000-85339-09",
        "tipo_de_cuenta" => "Corriente",
    ],
    "79937650-4" => [
        "razon_social_nombre" => "Panificadora Lo Saldes SA",
        "banco" => "Banco de Chile",
        "numero" => "00-162-12254-03",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78933370-K" => [
        "razon_social_nombre" => "Sociedad De Transportes Lo Saldes Ltda",
        "banco" => "Banco de Chile",
        "numero" => "00-800-23504-05",
        "tipo_de_cuenta" => "Corriente",
    ],
    "79864770-9" => [
        "razon_social_nombre" => "Lubricantes Internacionales Ltda",
        "banco" => "Santander",
        "numero" => "00-96536-7",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78803130-0" => [
        "razon_social_nombre" => "Magotteaux Andino SA",
        "banco" => "Santander",
        "numero" => "43-3984059-6",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78307010-3" => [
        "razon_social_nombre" => "Magotteaux Chile SA",
        "banco" => "Santander",
        "numero" => "2544993-2",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77661810-1" => [
        "razon_social_nombre" => "Mam Promociones Ltda",
        "banco" => "BCI",
        "numero" => "11813466",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76006946-9" => [
        "razon_social_nombre" => "Mam Est Ltda",
        "banco" => "BCI",
        "numero" => "45567484",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76495710-5" => [
        "razon_social_nombre" => "Comercial Marpaggi Ltda",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "76349975-8" => [
        "razon_social_nombre" => "Mega Frío Chile SA",
        "banco" => "BCI",
        "numero" => "10650890",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76042103-0" => [
        "razon_social_nombre" => "Megalogistica SA",
        "banco" => "Banco de Chile",
        "numero" => "9710801",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76228695-5" => [
        "razon_social_nombre" => "Empresa De Servicios Transitorios Interim Chile Ltda",
        "banco" => "ITAÚ",
        "numero" => "205241693",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76110319-9" => [
        "razon_social_nombre" => "Michael Page International Chile Ltda",
        "banco" => "ITAÚ",
        "numero" => "203979364",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76605074-3" => [
        "razon_social_nombre" => "Page Consulting Chile Ltda",
        "banco" => "ITAÚ",
        "numero" => "206926739",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76247511-1" => [
        "razon_social_nombre" => "Page Personnel International Chile Ltda",
        "banco" => "ITAÚ",
        "numero" => "205204649",
        "tipo_de_cuenta" => "Corriente",
    ],
    "86020700-1 " => [
        "razon_social_nombre" => "Michelin Chile Ltda",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "96557910-9" => [
        "razon_social_nombre" => "Alimentos Y Frutos SA (Santiago)",
        "banco" => "Banco Estado",
        "numero" => "472140",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96557910-9" => [
        "razon_social_nombre" => "Alimentos Y Frutos SA (Chillán)",
        "banco" => "Banco Estado",
        "numero" => "472140",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96557910-9" => [
        "razon_social_nombre" => "Alimentos Y Frutos SA (La Unión)",
        "banco" => "Banco Estado",
        "numero" => "472140",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96557910-9" => [
        "razon_social_nombre" => "Alimentos Y Frutos SA (Parral)",
        "banco" => "Banco Estado",
        "numero" => "472140",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96557910-9" => [
        "razon_social_nombre" => "Alimentos Y Frutos SA (Rengo)",
        "banco" => "Banco Estado",
        "numero" => "472140",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96557910-9" => [
        "razon_social_nombre" => "Alimentos Y Frutos SA (Romeral)",
        "banco" => "Banco Estado",
        "numero" => "472140",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96557910-9" => [
        "razon_social_nombre" => "Alimentos Y Frutos SA (San Carlos)",
        "banco" => "Banco Estado",
        "numero" => "472140",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96557910-9" => [
        "razon_social_nombre" => "Alimentos Y Frutos SA (San Fernando)",
        "banco" => "Banco Estado",
        "numero" => "472140",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76071027-K" => [
        "razon_social_nombre" => "Asesorias E Inversionaes Mv Services SA",
        "banco" => "Santander",
        "numero" => "63160504",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76077221-6" => [
        "razon_social_nombre" => "Mv Business SpA",
        "banco" => "Santander",
        "numero" => "63305758",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76333204-7" => [
        "razon_social_nombre" => "Empresa De Servicios Transitorios Mvs SpA",
        "banco" => "Santander",
        "numero" => "68589711",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77394530-6" => [
        "razon_social_nombre" => "Neoris Chile Ltda",
        "banco" => "Banco de Chile",
        "numero" => "0-105941-00-5",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76230085-0" => [
        "razon_social_nombre" => "Gimnasios Cordillera Limitada",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "76217448-0" => [
        "razon_social_nombre" => "Gimnasios La Cañada Ltda",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "76230685-9" => [
        "razon_social_nombre" => "Gimnasios Santiago Limitada",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "76244323-6" => [
        "razon_social_nombre" => "Sport Center Chile Ltda",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "79906540-1" => [
        "razon_social_nombre" => "Cargo Trader Ltda",
        "banco" => "Banco de Chile",
        "numero" => "1691030103",
        "tipo_de_cuenta" => "Corriente",
    ],
    "94528000-K" => [
        "razon_social_nombre" => "Evercrips Snack Productos De Chile SA",
        "banco" => "Banco de Chile",
        "numero" => "168-00708-08",
        "tipo_de_cuenta" => "Corriente",
    ],
    "59198550-7" => [
        "razon_social_nombre" => "Prodiel Agencia En Chile",
        "banco" => "Santander",
        "numero" => "67890345",
        "tipo_de_cuenta" => "Corriente",
    ],
    "91004000-6" => [
        "razon_social_nombre" => "Productos Fernandez SA",
        "banco" => "Banco de Chile",
        "numero" => "216-07070-08",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78201300-9" => [
        "razon_social_nombre" => "Servicios Generales Limitada",
        "banco" => "Banco de Chile",
        "numero" => "216-09376-07",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76839170-K" => [
        "razon_social_nombre" => "Proveedora Industrial Arrigoni SA",
        "banco" => "Santander",
        "numero" => "669417-9",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76670710-6" => [
        "razon_social_nombre" => "Servicios De Aseo Y Mantención Pure Clean Ltda",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "79639570-2" => [
        "razon_social_nombre" => "Quiborax SA",
        "banco" => "Scotiabank",
        "numero" => "640879605",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76083991-4" => [
        "razon_social_nombre" => "Rentco SA",
        "banco" => "Banco de Chile",
        "numero" => " 000-87228-08",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76138547-K" => [
        "razon_social_nombre" => "Mega Archivos SA",
        "banco" => "Banco de Chile",
        "numero" => "000-93648-00",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76156598-2" => [
        "razon_social_nombre" => "Mi Bodega SA",
        "banco" => "Banco de Chile",
        "numero" => " 000-95348-02",
        "tipo_de_cuenta" => "Corriente",
    ],
    "99581680-6" => [
        "razon_social_nombre" => "HQB SA",
        "banco" => "Scotiabank",
        "numero" => " 0-0097-01101-35",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76519803-8" => [
        "razon_social_nombre" => "Beer Garden Bellavista SpA",
        "banco" => "Banco de Chile",
        "numero" => "008001386904",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76150207-7" => [
        "razon_social_nombre" => "Santiago Wine SpA",
        "banco" => "Bice",
        "numero" => "1275508-2",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76253628-5" => [
        "razon_social_nombre" => "Brasserie Del Parque Forestal SpA",
        "banco" => "Banco de Chile",
        "numero" => "800-053-280-1",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78367000-3" => [
        "razon_social_nombre" => "Chipe Libre SpA",
        "banco" => "Banco de Chile",
        "numero" => "2860615754",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76327767-4" => [
        "razon_social_nombre" => "La Fabbrica SpA",
        "banco" => "BICE ",
        "numero" => "12766270",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76307561-3" => [
        "razon_social_nombre" => "Fuy SpA",
        "banco" => "BICE",
        "numero" => "12006578",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76296603-4" => [
        "razon_social_nombre" => "Uncle Fletch Chile SpA",
        "banco" => "BICE",
        "numero" => "12764006",
        "tipo_de_cuenta" => "Corriente",
    ],
    "79559220-2" => [
        "razon_social_nombre" => "Salmones Pacific Star SA",
        "banco" => "Santander",
        "numero" => "4737695",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96566740-7" => [
        "razon_social_nombre" => "Trusal SA",
        "banco" => "BCI-TBANC-BANCO NOVA",
        "numero" => "60289457",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76296099-0" => [
        "razon_social_nombre" => "Salmones Austral  SA",
        "banco" => "Santander",
        "numero" => "67461533",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77071440-0" => [
        "razon_social_nombre" => "Comsur SA",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "93565000-3" => [
        "razon_social_nombre" => "Ascensores Schindler Chile SA ",
        "banco" => "Santander",
        "numero" => "2573306-1",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96708800-5" => [
        "razon_social_nombre" => "Servicios Integrales De Cobranza",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "96928530-4" => [
        "razon_social_nombre" => "Comercial Automotriz SpA",
        "banco" => "BCI",
        "numero" => "10465006",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96676670-0" => [
        "razon_social_nombre" => "Comercial Chrysler SpA",
        "banco" => "BCI",
        "numero" => "10368591",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96555640-0" => [
        "razon_social_nombre" => "Comercial Itala SpA",
        "banco" => "BCI",
        "numero" => "10368591",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77076986-8" => [
        "razon_social_nombre" => "Gac Motor Chile SpA",
        "banco" => "BCI",
        "numero" => "10693254",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77529730-1" => [
        "razon_social_nombre" => "Inversiones Lb SpA",
        "banco" => "Santander",
        "numero" => "15526-8",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76126616-0" => [
        "razon_social_nombre" => "Iskb Chile SpA",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "96364000-5" => [
        "razon_social_nombre" => "Mmc Chile SA",
        "banco" => "BCI",
        "numero" => "10237526",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76033847-8" => [
        "razon_social_nombre" => "Nan Motors SpA",
        "banco" => "BCI",
        "numero" => "10605771",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76832940-0" => [
        "razon_social_nombre" => "Newco Motor Chile SpA",
        "banco" => "BCI",
        "numero" => "10588655",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96861240-9" => [
        "razon_social_nombre" => "Skberge Automotriz SpA",
        "banco" => "BCI",
        "numero" => "10441255",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76040171-4" => [
        "razon_social_nombre" => "Skberge Logistica SpA",
        "banco" => "BCI",
        "numero" => "10609938",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96929460-5" => [
        "razon_social_nombre" => "Skberge Luxury SpA",
        "banco" => "BCI",
        "numero" => "10464565",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76005843-2" => [
        "razon_social_nombre" => "South Pacific Motor Chile SpA",
        "banco" => "BCI",
        "numero" => "10596992",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76126616-0" => [
        "razon_social_nombre" => "Ssangyong Motor Chile SpA",
        "banco" => "BCI",
        "numero" => "10490744",
        "tipo_de_cuenta" => "Corriente",
    ],
    "79712500-8" => [
        "razon_social_nombre" => "Agrícola El Carrizal SA",
        "banco" => "Banco de Chile",
        "numero" => "00-000-6310-10",
        "tipo_de_cuenta" => "Corriente",
    ],
    "92261000-2" => [
        "razon_social_nombre" => "Industrias Metalúrgicas Sorena SA",
        "banco" => "Banco de Chile",
        "numero" => "85039-10",
        "tipo_de_cuenta" => "Corriente",
    ],
    "94565000-1" => [
        "razon_social_nombre" => "Pesquera Magallanes SA",
        "banco" => "BCI",
        "numero" => "10670246",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76275406-1" => [
        "razon_social_nombre" => "San Roberto Servicios Y Agencia De Negocios SA",
        "banco" => "Banco de Chile",
        "numero" => "800-02829-05",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96902390-3" => [
        "razon_social_nombre" => "Sorena Norte Grande SA",
        "banco" => "Banco de Chile",
        "numero" => "85014-04",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77063395-8" => [
        "razon_social_nombre" => "Sorena Servicios SA",
        "banco" => "Banco de Chile",
        "numero" => "800-41967-07",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96543160-8" => [
        "razon_social_nombre" => "Servicios Profesionales Globales SA",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "77329730-4" => [
        "razon_social_nombre" => "Inversiones Aguas Del Gran Santiago SA",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "76078231-9" => [
        "razon_social_nombre" => "Emp Depuradora De Aguas Servidas Mapocho Trebal Ltda",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "96799790-0" => [
        "razon_social_nombre" => "Servicios Y Proyectos Ambientales SA",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "77441870-9" => [
        "razon_social_nombre" => "Suez Medioambiente Chile SA",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "76495437-8" => [
        "razon_social_nombre" => "Suez Obras E Ingeniería SpA",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "76080553-k" => [
        "razon_social_nombre" => "Suez Advance Solutions Chile Ltda",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "76080553-K" => [
        "razon_social_nombre" => "Agualogy Solutions Chile Limitada",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "76432328-9" => [
        "razon_social_nombre" => "Ghm Gestión Hídrica Minera Ltda",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "76148998-4" => [
        "razon_social_nombre" => "Suez Medioambiente Chile Sa Rol General",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "76746454-1" => [
        "razon_social_nombre" => "Suez Biofactoria Andina SpA",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "111" => [
        "razon_social_nombre" => "Iam",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "89164000-5" => [
        "razon_social_nombre" => "Agroindustrial Surfrut Limitada",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "76760090-9" => [
        "razon_social_nombre" => "Est Service Ltda",
        "banco" => "Santander",
        "numero" => "6730566",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77325070-7" => [
        "razon_social_nombre" => "Team Work Consultora Ltda",
        "banco" => "Santander",
        "numero" => "2504898",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76646570-6" => [
        "razon_social_nombre" => "Teamwork Recursos Humanos Ltda",
        "banco" => "Santander",
        "numero" => "61582584",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77302440-5" => [
        "razon_social_nombre" => "Tecnored",
        "banco" => "BCI",
        "numero" => "15066011",
        "tipo_de_cuenta" => "Corriente",
    ],
    "85377600-9" => [
        "razon_social_nombre" => "Tefra Ingeniería Sanitaria SpA",
        "banco" => "BCI",
        "numero" => "10526722",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76031563-K" => [
        "razon_social_nombre" => "Tefra Proyectos Ltda",
        "banco" => "BCI",
        "numero" => "10605045",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76096227-9" => [
        "razon_social_nombre" => "Tefra Equipos Hidráulicos Ltda",
        "banco" => "BCI",
        "numero" => "10624104",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76105359-0" => [
        "razon_social_nombre" => "Tefra Servicios Empresariales SpA",
        "banco" => "BCI",
        "numero" => "10624091",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76616222-3" => [
        "razon_social_nombre" => "Comercial Mi Barrio Limitada",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "78090950-1" => [
        "razon_social_nombre" => "Tek Chile SA",
        "banco" => "BCI",
        "numero" => "10591257",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77983790-4" => [
        "razon_social_nombre" => "Tgf Clean SpA",
        "banco" => "BCI",
        "numero" => "29421195",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76058076-7" => [
        "razon_social_nombre" => "Tractebel Engineering SA",
        "banco" => "BCI",
        "numero" => "35416165",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76169670-K" => [
        "razon_social_nombre" => "Pesquera Trans Antartic Limitada",
        "banco" => "Santander",
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "79518000-1" => [
        "razon_social_nombre" => "Transportes Moneda Limitada",
        "banco" => "Banco de Chile",
        "numero" => "47693-05",
        "tipo_de_cuenta" => "Corriente",
    ],
    "86600000-K" => [
        "razon_social_nombre" => "Transporte Cerrillos Ltda",
        "banco" => "Banco de Chile",
        "numero" => "800-06702-09",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76102176-1" => [
        "razon_social_nombre" => "Empresa De Transportes Transvip SA",
        "banco" => "Santander",
        "numero" => "6390962-9",
        "tipo_de_cuenta" => "Corriente",
    ],
    "88670700-2" => [
        "razon_social_nombre" => "Unidad Coronaria Movil SA",
        "banco" => "Banco de Chile",
        "numero" => "162-73034-09",
        "tipo_de_cuenta" => "Corriente",
    ],
    "71543200-5" => [
        "razon_social_nombre" => "Universidad Adolfo Ibañez",
        "banco" => "Banco de Chile",
        "numero" => "14873087-06",
        "tipo_de_cuenta" => "Corriente",
    ],
    "71618600-8" => [
        "razon_social_nombre" => "Universidad Sek",
        "banco" => "Santander",
        "numero" => "62216085",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76046773-1" => [
        "razon_social_nombre" => "Uvz Mobiliario SpA",
        "banco" => null,
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "76092970-0" => [
        "razon_social_nombre" => "Verallia Chile SA",
        "banco" => "ITAÚ",
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "76058647-1" => [
        "razon_social_nombre" => "Verisure Chile SpA",
        "banco" => "Santander",
        "numero" => "6286868-6 ",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78279230-K" => [
        "razon_social_nombre" => "Agricola Frutos Del Maipo Limitada",
        "banco" => "Banco de Chile",
        "numero" => null,
        "tipo_de_cuenta" => "Corriente",
    ],
    "84356800-9" => [
        "razon_social_nombre" => "Watt´S SA",
        "banco" => "Banco de Chile",
        "numero" => "00-000-75695-04",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76455830-8" => [
        "razon_social_nombre" => "Diwatt´S SA",
        "banco" => "Banco de Chile",
        "numero" => "00-800-20226-00",
        "tipo_de_cuenta" => "Corriente",
    ],
    "90929000-7" => [
        "razon_social_nombre" => "Watt´S Comercial SA",
        "banco" => "Banco de Chile",
        "numero" => "00-800-04187-09",
        "tipo_de_cuenta" => "Corriente",
    ],
    "81140300-8" => [
        "razon_social_nombre" => "Williamson Industrial SA",
        "banco" => "Banco de Chile",
        "numero" => "056-63540314",
        "tipo_de_cuenta" => "Corriente",
    ],
    "96920980-2" => [
        "razon_social_nombre" => "Winpack SA",
        "banco" => "Banco de Chile",
        "numero" => "5163117154",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76737160-8" => [
        "razon_social_nombre" => "Workmate Est",
        "banco" => "BCI",
        "numero" => "45190500",
        "tipo_de_cuenta" => "Corriente",
    ],
    "77815160-K " => [
        "razon_social_nombre" => "Workmate SA",
        "banco" => "BCI",
        "numero" => "13337092",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76145470-6" => [
        "razon_social_nombre" => "Servicios de Atencion Domiciliaria S.A",
        "banco" => "Santander",
        "numero" => "3296911",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76368969-7" => [
        "razon_social_nombre" => "Servicios Integrales Técnicos y Administrativos GO S.A",
        "banco" => "Santander",
        "numero" => "69457053",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76943147-0" => [
        "razon_social_nombre" => "Anar Gestion Empresarial ",
        "banco" => "BCI",
        "numero" => "21657165",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76798330-1" => [
        "razon_social_nombre" => "GO Empresa de Servicios Transitorios S.A",
        "banco" => "Santander",
        "numero" => "6697941",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76216268-7" => [
        "razon_social_nombre" => "Grupo Colchagua EST S.A.",
        "banco" => "Banco de Chile",
        "numero" => "1630418801",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76375337-9" => [
        "razon_social_nombre" => "Grupo Santa Cruz Outsourcing",
        "banco" => "Banco de Chile",
        "numero" => "1630572507",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76458900-9" => [
        "razon_social_nombre" => "SERVICIOS INDUSTRIALES INTEGRA LTDA",
        "banco" => "Santander",
        "numero" => "5487765",
        "tipo_de_cuenta" => "Corriente",
    ],
    "78834140-7" => [
        "razon_social_nombre" => "CAP SERV ASESORIA Y REPR INTEGRA",
        "banco" => "Santander",
        "numero" => "4532376",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76735710-9" => [
        "razon_social_nombre" => "EMP. DE SERV. TRANSITORIOS INTEGRA LTDA.",
        "banco" => "Santander",
        "numero" => "6353479",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76977820-9" => [
        "razon_social_nombre" => "SOC DE TRANSPORTES INTEGRA LTDA",
        "banco" => "Santander",
        "numero" => "63890626",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76050022-4" => [
        "razon_social_nombre" => "SOCIEDAD CONSTRUCTORA B Y F LIMITADA",
        "banco" => "Santander",
        "numero" => "72566106",
        "tipo_de_cuenta" => "Corriente",
    ],
    "76455338-1" => [
        "razon_social_nombre" => "SOC COM CONSTRUCCION Y TRANS GLOBAL LTDA",
        "banco" => "Santander",
        "numero" => "72979699",
        "tipo_de_cuenta" => "Corriente",
    ],
];